### PR TITLE
showing correct kids picture

### PR DESCRIPTION
**Pull request by houseburger**
since every section, besides the kids section, only has one image, we
can use first() instead of last(), then it should show the correct
image on every square/rectangle

### CODE REVIEW

**Comment by houseburger** [comment]
@iamtimm yup, changed it now! :)

**Comment by timothyachumba** [comment]
Hey so you're aware that you have to change the background images on the server? The content folder doesn't get deployed.

**Comment by houseburger** [comment]
yeah sure ;)
all the names are changed to 01, and in the kids section, there are 2 photos, 01 and 02.
screen shot 2015-03-12 at 6 53 31 pm

**Comment by timothyachumba** [comment]
Yeah looks good. Just a note, the file size for the image is too large. 1.04 mb is a lot.

-- 
Timothy Achumba
Sent with Airmail

On 12 March 2015 at 18:55:40, hauspa (notifications@github.com) wrote:

yeah sure ;)
all the names are changed to 01, and in the kids section, there are 2 photos, 01 and 02.

**Comment by houseburger** [comment]
yup, thanks for the info, didnt realize. it's reduced to 160kb now ;)

**Pull request merged**
